### ISSUE TITLE
[Unidentified Tracker]: SalesViewer via gtmrkt.com

### ISSUE THREAD

**Issue by floss-51nullacht** [ghostery/trackerdb#475]
### Request

https://gtmrkt.com/stm.js?id=xyz

### Location

https://www.weichertmehner.com/

### Tracker Company

SalesViewer

### Company Website

https://www.salesviewer.com/

### Privacy Policy

https://www.salesviewer.com/de/datenschutzerklaerung/

### Category

Advertising

### Request Type

None

**Comment by philipp-classen** [comment]
Thanks, I updated it: https://github.com/ghostery/trackerdb/pull/476.

Note: if you are aware of a source that states that gtmrkt.com and salesviewer.com are related, please share. But I also believe it is the case, because gtmrkt.com links to salesviewer.com. Not a proof, but likely enough given the information that we have.
